dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  
  # State Management
  provider: ^6.1.1
  
  # UI & Utilities
  image_picker: ^1.0.7
  intl: ^0.18.1
  cached_network_image: ^3.3.1
  
  cupertino_icons: ^1.0.2